application: lastingstatement
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /texas
  static_dir: texas
- url: /bootstrap
  static_dir: bootstrap
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: django
  version: 1.2

builtins:
- remote_api: on
